#+title: ASTR170 B1 Session 002 - Syllabus
#+author: Mathieu Renzo
#+email: mrenzo@arizona.edu
#+PREVIOUS_PAGE: index.org
#+NEXT_PAGE: schedule.org

* Description of the course

This course tells the story of how astronomers explore our Universe.
You will engage in a variety of activities that illustrate historical
and contemporary ideas and methods which reveal the mysteries of the
Cosmos. Astronomy will be placed in a cultural context that allows you
to reflect on the relevance of science in society today.

* Where and when
Steward Observatory, room N210, Monday-Wednesday 2:00pm-3:15pm

* Instructors
** Prof. [[https://lavinia.as.arizona.edu/~mrenzo/index.html][Mathieu Renzo]]
- Office: Steward Observatory N506
- Email: [[mailto:mrenzo@arizona.edu][mrenzo@arizona.edu]], please include "170B1" in email subject
- Office hours: by appointment to be scheduled by email

** TA Neev Shah
- Office: Steward Observatory 302
- Email: [[mailto:neevshah@arizona.edu][neevshah@arizona.edu]], please include "170B1" in email subject
- Office hours: Wednesday 1:00pm-2:00pm Steward Observatory library
  (N304) or by appointment

*N.B.:* *Office hours are times set aside to help you!* Please come and
ask any questions you have. My availability is different every week,
so please reach out to schedule an appointment. Email is the best way
to get in touch with us, but given our schedule, we may not respond
for a full business day. Please plan ahead.

* Required textbook and resources
/The Cosmic Perspective/, 10^{th} edition By Bennett, et al. (Pearson) with
/Mastering Astronomy/ website. See [[./access_howto.org][detailed instructions on how to
access the materials]].

* Exams and grading

|---------------+-----------------------+--------+-------+------|
|               | Number                | Points | Total |    % |
|---------------+-----------------------+--------+-------+------|
| Midterms      | 2                     |    100 |   200 |   25 |
| Final exam    | 1                     |    100 |   100 | 12.5 |
| Homework/Labs | 14 (lowest 2 dropped) |     20 |   240 |   30 |
| Quizzes       | 13 (lowest 1 dropped) |      5 |    60 |  7.5 |
| Participation | 24 (lowest 4 dropped) |      3 |    60 |  7.5 |
| Signature Lab | 1                     |    140 |   140 | 17.5 |
|---------------+-----------------------+--------+-------+------|
| Total         |                       |        |   800 |  100 |
|---------------+-----------------------+--------+-------+------|

** Letter Grading
A: 90-100%; B: 80-89%; C: 65-79%; D: 50-64%; E: <50%

We reserve the right to make the grading slightly easier, but will not
raise these thresholds. Under no circumstances will anyone doing less
than 50% work pass this class.

** Participation
This is an in-person class and regular attendance is expected.
Participation will be measured electronically at each lecture using
the [[https://help.intech.arizona.edu/article/397-what-is-top-hat][Top Hat]] app. *N.B.:* You may miss up to 4 lectures for any reason
without affecting your participation grade.

Top Hat will run on a phone, tablet or laptop. You are responsible to
bring your device to every class period. To encourage you to do so, we
will give you participation points for using your device in class.
Students who forget to bring their device to class will not receive
participation points. You will receive points if you have an official
excuse from the Dean of Students Office, a note from a health care
provider, or you are observing a religious holiday which is associated
with an organized religion to which you belong, as outlined in the
links below. You are responsible for informing Prof. Renzo promptly if
this is the case.
- Participation points will be awarded for completion not correctness.
  These questions are designed to improve your understanding of the
  material and lead to a better grade. So be smart, attend class!
- Students are responsible for all information given out in the
  lecture, including schedule changes. The UA’s policy concerning
  Class Attendance, Participation, and Administrative
  Drops:https://catalog.arizona.edu/policy/class-attendance-and-participation.
  The UA policy regarding absences for any sincerely held religious
  belief, observance or practice will be accommodated where
  reasonable,
  http://policy.arizona.edu/human-resources/religious-accommodation-policy.
- Absences pre-approved by the UA Dean of Students (or Dean Designee)
  will be honored. See: https://deanofstudents.arizona.edu/absences
- If you feel sick or may have been in contact with someone who is
  infectious, stay home. Except for seeking medical care, avoid
  contact with others.
- Notify your instructors if you will be missing a lecture. If you
  miss a lab or exam for documented illness or another allowed reason,
  it is your responsibility to contact Prof. Renzo for a makeup
  option. *DO THIS EARLY*, do not wait until the end of the semester.
  All lecture slides will be posted to D2L.

** Exams
Midterm and final exam will be in class closed-book/notes exams.
Nothing may be on your desk aside from your Top Hat device during the
exam. Any attempt to access non-exam materials will result in an
immediate failure. If you have any accessibility concerns about the
exam format, please reach out to the DRC and Prof. Renzo prior to the
exam to work out any accommodations.

** Weekly online homework
On most Tuesdays at 11:59pm an homework assignment will be due (see
[[./schedule.org][schedule]]). *All assignments will be submitted electronically*.
# Two attempts per questions should be possible.
Late submissions are allowed until Wednesday 11:59pm, but with 50%
penalty on the grade for the parts submitted late.

You should access Mastering Astronomy through Brightspace from the
Content tab of our course webpage (see [[./access_howto.org][how to]]). You may discuss the
astronomy concepts with your classmates, but you are expected to do
your own work on these assignments.

Grades will be posted on Brightspace as soon as possible after the
assignment is collected. Any questions, disputes, or mistakes must be
identified and brought to Neev Shah and/or Prof. Renzo’s attention
within 3 business days of the grade being posted. After that, all
grades are finalized, although questions are still answered.

You have *one free no questions asked 3-day-late* (72 hours after the
due date/time) turn in for one homework assignment that can be used by
you in case of dire need. Note that this *CANNOT* be used for the
Signature Assignment. Please inform Neev Shah and Prof. Renzo on the
day the assignment is due to use this late turn in. Sometimes everyone
has a difficult day. Assignments can be turned in early if desired.
Please do not provide any details. Otherwise, homework turned in late
will be graded, with a 50% late penalty. This applies to all Mastering
Astronomy assignments, Labs, and the Mastering tutorials of the
Signature Assignment, but NOT the Signature Assignment Digication
ePortfolio.If you have extenuating circumstances which cannot be met
by this policy, please inform the Professor. The final deadline to
turn in any late work is Saturday, December 12 at 11:59pm.

** In-class Labs
There are three labs throughout the semester (see [[./schedule.org][schedule]]),
consisting of an in-class activity and follow up questions. Each lab
worksheet will be distributed in class and must be completed, scanned,
and turned in electronically via Brightspace. A lab makeup will only
be allowed for an excused absence as defined below; please contact
Prof. Renzo.

** In-class quizzes
Most Wednesdays we are going to start with a "homework quiz". One
question from the assignment due the night before will be administered
on Top Hat and graded for correctness. Mastering Astronomy allows you
to view the correct answer after completion, so this should be easy if
you have actually done (and understood) the homework.

** Signature Assignment
Using Telescopes to Explore our Universe is the title of your
Signature Assignment. You will use the Steward Observatory 21-Inch
Telescope, the Seestar S50 telescope/camera, and your smart phone to
make astronomical observations. The assignment, accessed through D2L,
will begin in September and last all semester. Final reports will be
due by Nov. 26 at 5:00 p.m. MST.

** Honors credit
This course is *not* available for Honors credit via an Honors contract.
We are offering an Honors section of ASTR 170B1 (Sec 003H) which meets
on TTh 9:30 – 10:45 a.m. in SO N210. Should you wish to receive Honors
credit for ASTR 170B1, please drop this course section and enroll in
Section 003H.

* Expected learning outcomes
ASTR 170B1 is an "Exploring Perspectives: Natural Scientist course" in
the *new* University of Arizona General Education program (Tier 1
Natural Sciences). Upon completion of this course, students will be
able to:
- identify the approaches and methodologies of Natural Scientists,
  using evidence to critically analyze questions and arguments, and
  consider contributions of this perspective to finding solutions to
  global and/or local challenges. (Exploring Perspectives: Natural
  Scientist SLO)
- demonstrate competency in working with numerical information by
  critically analyzing quantitative information, generate ideas that
  are supported by quantitative evidence, assess the relevance of data
  and its associated implications in a variety of contexts, and
  communicate those ideas and/or associated interpretations using
  various formats (graphs, data tables, equations, oral presentations,
  or written reflections. (Quantitative Reasoning Attribute SLO)

More specifically, upon completion of this course you should be able
to:
1. Practice taking the unique perspectives of the astronomer.
2. Apply the perspective of the astronomer to understand and evaluate
   our current concepts of the structure and scale of our Universe.
3. Demonstrate knowledge of the physical processes (e.g., gravity,
   nuclear reactions, light) that operate in our Universe and use this
   knowledge to draw conclusions from data that answer astronomical
   questions.
4. Communicate ideas in various ways including verbally, with
   drawings, diagrams, in writing, and in quantitative formats such as
   graphs, tables and equations.
5. Critically analyze astronomical data presented in various
   quantitative formats to identify inconsistencies, contradictions &
   inaccuracies.
6. Collaborate with their peers to analyze, evaluate, and interpret
   these data.
7. Summarize and evaluate competing arguments that have been made to
   explain astronomical phenomena.
8. Engage in discourse, develop explanatory models, and make
   scientific predictions.
9. Discern the meaning of discipline representations and develop
   discipline fluency.
10. Reflect on the role and importance and contributions of science
    and astronomy in our society

These learning outcomes will be met through attendance at lectures,
in-class activities, homework and writing assignments, and a final
project.

*N.B.:* You are encouraged to ask questions in class and to seek help if
needed. It is to your advantage to seek help when you encounter
problems rather than at the last minute before a deadline. We are here
to help you understand something about science and the subject of
astronomy!

* Statement on Generative AI
You are welcome to use generative AI tools as part of your learning
process in this course. These tools can be valuable aids for exploring
concepts and organizing your thoughts. However we *strongly* encourage
you to try to solve all problems on your own first and to instead
consult a verified source like your lecture notes or course textbook.
Ultimately, you are responsible for your own understanding of the
course material. Use of any AI tool during an exam is prohibited.

/All work you submit must represent your own understanding, analysis,
and intellectual effort/. When you use generative AI in preparing an
assignment, you must:

1. Declare its use and describe how you employed it, for example: /"I
   acknowledge the use of/ <insert AI> /t/o <describe specific use>
   /with the following/ <link or copy paste prompt>." (see also [[https://libguides.library.arizona.edu/students-chatgpt/citing][the
   University Libraries Guidelines]])
2. Provide answers, solutions, and interpretations that reflect your
   own reasoning and expertise.

Submitting AI-generated content as your own work - whether in whole or
in part - constitutes a violation of the [[https://deanofstudents.arizona.edu/policies/code-academic-integrity][Code of Academic Integrity]],
specifically the prohibition against submitting work that is not your
own. This includes text, code, calculations, or analyses that you have
not personally verified, understood, and made your own through genuine
intellectual engagement. If you have questions about appropriate use
of AI tools for a particular assignment, please ask before engaging
with the tool.

* Classroom Behavior
To foster a positive learning environment, students and instructors
have a shared responsibility. We want a safe, welcoming, and inclusive
environment where all of us feel comfortable with each other and where
we can challenge ourselves to succeed. To that end, our focus is on
the tasks at hand and not on extraneous activities (e.g., texting,
chatting, web surfing, etc.). Students are asked to refrain from
disruptive conversations with people sitting around them during
lecture. Students observed engaging in disruptive activity will be
asked to cease this behavior. Those who continue to disrupt the class
will be asked to leave lecture or discussion and may be reported to
the Dean of Students.

# The Arizona Board of Regents’ Student Code of Conduct, ABOR Policy
# 5‐308, prohibits threats of physical harm to any member of the
# University community, including to one’s self. See:
# [[http://policy.web.arizona.edu/threatening‐behavior‐students]]

# Any social media groups generated using university-sponsored tools
# (e.g., D2L class lists, slack workspaces) should be treated as an
# extension of the classroom. This means that they will need to abide by
# the University’s student code of conduct policies, and be respectful,
# inclusive environments.

# ** Nondiscrimination and Anti-harassment Policy
# The University of Arizona is committed to creating and maintaining an
# environment free of discrimination. In support of this commitment, the
# University prohibits discrimination, including harassment and
# retaliation, based on a protected classification, including race,
# color, religion, sex, national origin, age, disability, veteran
# status, sexual orientation, gender identity, or genetic information.
# For more information, including how to report a concern, please see
# http://policy.arizona.edu/human-resources/nondiscrimination-and-anti-harassment-policy

** Accessibility and accommodations
At the University of Arizona, we strive to make learning
experiences as accessible as possible. If you anticipate or
experience barriers based on disability or pregnancy, please
contact the Disability Resource Center (520-621-3268,
https://drc.arizona.edu/) to establish reasonable accommodations.

** Class recordings
To facilitate everyone's participation, audio and/or video recording
of in class activities is *not allowed* unless explicitly agreed upon by
all present students /and/ instructors. In no case sharing on public
platforms of the recordings will be allowed.

* Academic Integrity

Students are encouraged to share intellectual views and discuss freely
the principles and applications of course materials. However, graded
work/exercises must be the product of independent effort unless
otherwise instructed. /Presentation of any work other than your own is
considered academic dishonesty/. This includes copying test answers or
homework assignments, failing to cite external references consulted or
quoted in assignments, other persons taking exams for you, or
reference to any unauthorized materials during an exam. All students
must be prepared to present valid picture identification if requested
during an exam period.

The University Libraries have some excellent tips for avoiding
plagiarism, available at
https://lib.arizona.edu/research/citing/plagiarism Any other technique
that gains unfair advantage over other students is also considered
academically dishonest. Any incidents of academic dishonesty will be
dealt with according to the University of Arizona's Code of Academic
Integrity. This Code can be viewed at the Dean of Students website:
https://deanofstudents.arizona.edu/policies/code-academic-integrity
The consequences can range from loss of credit on an assignment to
dismissal from the University, depending on the severity of the
offense. In our class, the penalty for intentional plagiarism,
cheating on an exam, or computer fraud will be automatic failure of
the course and, depending on the circumstances, Prof. Renzomay
seek your suspension or expulsion from the University.

* Confidentiality of Student Records
http://www.registrar.arizona.edu/ferpa

* University policies
All students must familiarize themselves with the policies and resources at
the following link: https://catalog.arizona.edu/syllabus-policies.

* Subject to change statement
The information contained in this syllabus, other than the grade and absence
policies, may be subject to change with reasonable advance notice, as deemed
appropriate by the instructor.
