#+title: ASTR170 B1 Session 002 - Syllabus
#+author: Mathieu Renzo
#+email: mrenzo@arizona.edu
#+PREVIOUS_PAGE: index.org
#+NEXT_PAGE: schedule.org



* Description of the course

* Where and when
Steward Observatory, room N210, Monday-Wednesday 2:00pm-3:15pm

* Instructors
** Prof. [[https://lavinia.as.arizona.edu/~mrenzo/index.html][Mathieu Renzo]]
- Office: Steward Observatory N506
- Email: [[mailto:mrenzo@arizona.edu][mrenzo@arizona.edu]]
- Office hours: by appointment to be scheduled by email
** TA Neev Shah
- Office: Steward Observatory 302
- Email: [[mailto:neevshah@arizona.edu][neevshah@arizona.edu]]
- Office hours: Wednesday 1:00pm-2:00pm

*N.B.:* *Office hours are times set aside to help you!* Please come and
ask any questions you have. My availability is different every week,
so please reach out to schedule an appointment. Email is the best way
to get in touch with me, but given my schedule, I may not respond for
a full business day. Please plan ahead.

* Required textbook and resources
/The Cosmic Perspective/, 10 th edition By Bennett, et al. (Pearson)
with /Mastering Astronomy/ website accessible through [[https://d2l.arizona.edu/d2l/home/1802755][D2L]].
* TODO Expected learning outcomes

These learning outcomes will be met through attendance at lectures,
in-class activities, homework and writing assignments, and a final
project.

*N.B.:* You are encouraged to ask questions in class and to seek help if
needed. It is to your advantage to seek help when you encounter
problems rather than at the last minute before a deadline. We are here
to help you understand something about science and the subject of
astronomy!

* TODO Exams and grading

- A: 90-100%
- B: 80-89%
- C: 65-79%
- D: 50-64%
- E: <50%

We reserve the right to make the grading slightly easier, but will not
raise these thresholds. Under no circumstances will anyone doing less
than 50% work pass this class.

** TODO Assignments

** TODO Signature Assignment
Using Telescopes to Explore our Universe is the title of your
Signature Assignment. You will use the Steward Observatory 21-Inch
Telescope, the Seestar S50 telescope/camera, and your smart phone to
make astronomical observations. The assignment, accessed through D2L,
will begin in September and last all semester. Final reports will be
due by Nov. 26 at 5:00 p.m. MST.

** Honors credit
This course is *not* available for Honors credit via an Honors contract.
We are offering an Honors section of ASTR 170B1 (Sec 003H) which meets
on TTh 9:30 – 10:45 a.m. in SO N210. Should you wish to receive Honors
credit for ASTR 170B1, please drop this course section and enroll in
Section 003H.

* Statement on Generative AI
You are welcome to use generative AI tools as part of your learning
process in this course. These tools can be valuable aids for exploring
concepts and organizing your thoughts. However we *strongly* encourage
you to try to solve all problems on your own first and to instead
consult a verified source like your lecture notes or course textbook.
Ultimately, you are responsible for your own understanding of the
course material. Use of any AI tool during an exam is prohibited.

/All work you submit must represent your own understanding, analysis,
and intellectual effort/. When you use generative AI in preparing an
assignment, you must:

1. Declare its use and describe how you employed it, for example:
   "I acknowledge the use of <insert AI> to <describe specific use> with the following <link or copy paste prompt>."
   (see also [[https://libguides.library.arizona.edu/students-chatgpt/citing][the University Libraries Guidelines]])
2. Provide answers, solutions, and interpretations that reflect your
   own reasoning and expertise.

Submitting AI-generated content as your own work - whether in whole or
in part - constitutes a violation of the [[https://deanofstudents.arizona.edu/policies/code-academic-integrity][Code of Academic Integrity]],
specifically the prohibition against submitting work that is not your
own. This includes text, code, calculations, or analyses that you have
not personally verified, understood, and made your own through genuine
intellectual engagement. If you have questions about appropriate use
of AI tools for a particular assignment, please ask before engaging
with the tool.

* Classroom Behavior
To foster a positive learning environment, students and instructors
have a shared responsibility. We want a safe, welcoming, and inclusive
environment where all of us feel comfortable with each other and where
we can challenge ourselves to succeed. To that end, our focus is on
the tasks at hand and not on extraneous activities (e.g., texting,
chatting, web surfing, etc.). Students are asked to refrain from
disruptive conversations with people sitting around them during
lecture. Students observed engaging in disruptive activity will be
asked to cease this behavior. Those who continue to disrupt the class
will be asked to leave lecture or discussion and may be reported to
the Dean of Students.

The Arizona Board of Regents’ Student Code of Conduct, ABOR Policy
5‐308, prohibits threats of physical harm to any member of the
University community, including to one’s self. See:
[[http://policy.web.arizona.edu/threatening‐behavior‐students]]

Any social media groups generated using university-sponsored tools
(e.g., D2L class lists, slack workspaces) should be treated as an
extension of the classroom. This means that they will need to abide by
the University’s student code of conduct policies, and be respectful,
inclusive environments.

** Nondiscrimination and Anti-harassment Policy
The University of Arizona is committed to creating and maintaining an
environment free of discrimination. In support of this commitment, the
University prohibits discrimination, including harassment and
retaliation, based on a protected classification, including race,
color, religion, sex, national origin, age, disability, veteran
status, sexual orientation, gender identity, or genetic information.
For more information, including how to report a concern, please see
http://policy.arizona.edu/human-resources/nondiscrimination-and-anti-harassment-policy

** Accessibility and accommodations
At the University of Arizona, we strive to make learning
experiences as accessible as possible. If you anticipate or
experience barriers based on disability or pregnancy, please
contact the Disability Resource Center (520-621-3268,
https://drc.arizona.edu/) to establish reasonable accommodations.

** Class recordings
To facilitate everyone's participation, audio and/or video recording
of in class activities is *not allowed* unless explicitly agreed upon by
all present students /and/ instructors. In no case sharing on public
platforms of the recordings will be allowed.

** Preferred Name and Pronoun
This course affirms people of all gender expressions and gender
identities. If you prefer to be called a different name than what is
on the class roster, please let me know. Feel free to correct
instructors on your preferred gender pronoun.

* Attendance Policy
All holidays or special events observed by organized religions will be
honored for those students who show affiliation with that particular
religion. Absences pre‐approved by the UA Dean of Students (or Dean's
designee) will be honored.

It is important to attend all classes, as what is discussed in class
is pertinent to adequate performance on assignments and exams. If you
must be absent, it is your responsibility to obtain and review the
information you missed.

* Academic Integrity
Integrity is expected of every student in all academic work. The
guiding principle of academic integrity is that a student’s submitted
work must be the student’s own. Students are encouraged to share
intellectual views and discuss freely the principles and applications
of course materials. However, *graded work/exercises must be the
product of your own effort unless otherwise instructed*. Students are
expected to adhere to the UA Code of Academic Integrity as described
in the UA General Catalog. See:
[[https://deanofstudents.arizona.edu/student-rights-responsibilities/academic-integrity]]

Misappropriation of exams before or after they are given will be
considered academic misconduct. Misconduct of any kind will be
prosecuted and may result in any or all of the following:
- Reduction of grade
- Failing grade
- Referral to the Dean of Students for consideration of additional
  penalty, i.e. notation on a student’s transcript re. academic
  integrity violation, etc. [[http://deanofstudents.arizona.edu/policies‐and‐codes/code‐academic‐integrity]]

* Additional resources for students
UA Academic policies and procedures are available at
http://catalog.arizona.edu/policies

** Campus Health
http://www.health.arizona.edu/

Campus Health provides quality medical and mental health care services
through virtual and in-person care.

- Phone: 520-621-9202

** Counseling and Psych Services (CAPS)
https://health.arizona.edu/counseling-psych-services

CAPS provides mental health care, including short-term counseling
services.

- Phone: 520-621-3334

** The Dean of Students Office’s Student Assistance Program
http://deanofstudents.arizona.edu/student-assistance/students/student-assistance

Student Assistance helps students manage crises, life traumas, and
other barriers that impede success. The staff addresses the needs of
students who experience issues related to social adjustment, academic
challenges, psychological health, physical health, victimization, and
relationship issues, through a variety of interventions, referrals,
and follow up services.

- Email: [[mailto:DOS-deanofstudents@email.arizona.edu][DOS-deanofstudents@email.arizona.edu]]
- Phone: 520-621-7057

** Survivor Advocacy Program
https://survivoradvocacy.arizona.edu/

The Survivor Advocacy Program provides confidential support and
advocacy services to student survivors of sexual and gender-based
violence. The Program can also advise students about relevant non-UA
resources available within the local community for support.

- Email: [[mailto:survivoradvocacy@email.arizona.edu][survivoradvocacy@email.arizona.edu]]
- Phone: 520-621-5767

** Support Outreach Success (SOS)
https://sos.arizona.edu/about

Students who ask for help are more successful. If you have questions,
concerns or challenges and are unsure about where to go for answers or
support you can ask SOS. The SOS staff will answer questions, find you
resources or connect you with the correct people. Whether you’re
brand-new to campus or have been around for a while, just reach out to
SOS for support.

- Chat: [[http://sos.arizona.edu][sos.arizona.edu]]
- Email: [[mailto:sos@arizona.edu][sos@arizona.edu]]
- Text: SOS to 70542
- Call: 520-621-2327

* Confidentiality of Student Records
http://www.registrar.arizona.edu/ferpa

* Safety on Campus and in the Classroom
For a list of emergency procedures for all types of incidents, please visit the website of the Critical
Incident Response Team (CIRT): https://cirt.arizona.edu/case-emergency/overview

Also watch the video available at
https://arizona.sabacloud.com/Saba/Web_spf/NA7P1PRD161/common/learningeventdetail/crtfy000000000003560

* Subject to change statement
The information contained in this syllabus, other than the grade and absence
policies, may be subject to change with reasonable advance notice, as deemed
appropriate by the instructor.
